### ISSUE TITLE
BPMN Designer Tool

### ISSUE THREAD

**Issue by nourBerro** [roger-castaldo/BPMEngine#1]
You have done a great job, im wondering if you are using any bpmn designer tool?

**Comment by roger-castaldo** [comment]
I use https://bpmn.io/
However you will likely have to build your own page using their js and expanding the moddle library with the moddle.json file located in the code to handle the extended elements, it does not seem to handle them well.

**Comment by nourBerro** [comment]
Thats great accually im also worked with bpmn.io but i didnt know how to add your js files to extend the functions.

Im wondring if you are working on developing bpm system using .net  i hope we can work together

**Comment by roger-castaldo** [comment]
I currently have a closed source project that I jave been playing with written in .net that is in the beta stage as I am still implementing some of the core functionality and trying to decide if I want to open source it and license out a support model or license out the software itself.  I will keep you posted.

**Comment by nourBerro** [comment]
Im working on closed software as well.
But the market doesnt need more than one bpm .net thats why i asked you.
Anyway i will be here when u decide.
