### ISSUE TITLE
How to extend this project?

### ISSUE THREAD

**Issue by hnsnhy** [roger-castaldo/BPMEngine#10]
hello roger-castaldo:
I am very happy to see your project. This is the only project I can find to support the standard BPMN XML file. Now I have a few questions I would like to ask you:
1. What if I need to extend related properties and classes? Because I saw that the type basically adds "internal".
2, I saw that you mentioned bpmn.io when answering related questions. When I use this tool to generate xml files, I have a large number of "camunda" prefix attributes. How can I extend your class library and parse it? For example, in "userTask" contains "camunda:formKey"?
Thank you

**Comment by roger-castaldo** [comment]
1.  The library itself was built around a bit of a black box principal so extending the internal elements is not really doable.  However, through implementing the delegates for the Process Instance, you can interface with the elements as they are being called.
2.  To access non-standard attributes, simply take the element passed in through a delegate, which at minimum should be an IElement, and call IElement["attribute name"] for example IElement["camunda:formKey"] should return the string value of the given attribute, or null if not set.  The other option, based off of bpmne standards, you can add additional xml to the bpmn:extensions element that contains comonponents to be used and can be access via IElement.SubNodes.

**Comment by hnsnhy** [comment]
Thank you very much for your answer, I will try to use the method you provided.
