### ISSUE TITLE
Code examples

### ISSUE THREAD

**Issue by pitchcontrol** [roger-castaldo/BPMEngine#11]
Please add some examples of using, may be a sample project etc.

**Comment by roger-castaldo** [comment]
There is a sample project with code attached to the closed issue #8.  When I have more time I will try to put something in either the release downloads or into the documentation.

**Comment by josersleal** [comment]
Hello

Would be appreciated if you'd be able to create some meaningful example code. Working code of course.
Also a better documentation would be useful. Usage and architecture.

**Comment by roger-castaldo** [comment]
I am currently working on some more detailed, better written and updated documentation.  As far  meaningful sample code, the problem there is I would first have to write a business process and a program to interface with it.  That is a bit on the difficult side for me to find the time for both aspects currently.

**Comment by roger-castaldo** [comment]
I have updated the commenting for the library found inside the Wiki.

**Comment by rayzhb** [comment]
hello, how to use ConditionsPanel.js ?

**Comment by roger-castaldo** [comment]
[modeler.zip](https://github.com/roger-castaldo/BPMEngine/files/7131391/modeler.zip)
attached is a sample html page showing how to call the conditions panel.  There is a bug with it that doesn't allow the creation of condition sets that I will look into at some point but you can see the idea on how to use it.
