### ISSUE TITLE
why exclusiveGateway only execute first outgoing? I had add bpmn:conditionExpression  but no effect

### ISSUE THREAD

**Issue by qianqianda** [roger-castaldo/BPMEngine#17]

**Comment by roger-castaldo** [comment]
The defalut IsFlowValid delegate returns true.  If you have not used the extension elements ConditionSet and have not both implemented and supplied a delegate for isFlowValid, it will always default to the first one.  

That being said, I have now added a patch to supply the conditionExpression from a sequence flow element if it exists when being supplied to the IsFlowValid delegate to allow for a user to implement their own checks based on the variable value.  I have also instituted an exception to fail the exclusive gateway if and when it finds more than 1 valid outgoing path.  All changes have been deployed to the 2.0 branch which will be deployed soon as a beta nuget package for more thorough testing.
