### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Diaskhan** [roger-castaldo/BPMEngine#5]
Dear Roger.
I have a suggestion to U.
I'm  planing to develop BPM+ECM system.

Maybe we unite our forces to develop something similar to Activiti BPM.

If U interested I could present a my vision of it !

**Comment by Diaskhan** [comment]
Soon nhibernate will be ported to net core. 
In 2.1 net core gonna will fix DirectoryServices.
If will be some kind bpm of workflow in net.core, there net core could concurent with java in enterprise sector!

**Comment by nourBerro** [comment]
Im interesting

**Comment by Diaskhan** [comment]
I have searched many repo.
Many users have their own implementation of bpm. But many people didnt finished implementation !
To develop bpm system of enterprise level, we could gather team, that interested in developing Bpm system, the ecm and bpm system is very fragmented !

Develope bpms system is to heavy for one developer !

**Comment by nourBerro** [comment]
I have developed bpm with old WWF and asp.net web from many years ago 
And i have very good idea about this kind of systems.

**Comment by Diaskhan** [comment]
Did U heard about Elma Bpm 
http://www.elma-bpm.com/elma-community/

Its not only a bpm sytem, there have bpm+ecm+crm+projects ,It's very Exciting!  
That system not only folows one bpm direction, there have united all products  in one System!

Maybe we shall comunicate in social network ???

**Comment by Diaskhan** [comment]
nourBerro ???

**Comment by nourBerro** [comment]
Im open to any suggestions

**Comment by Diaskhan** [comment]
Do U have a messenger ??
Maybe tomorow will could speak about plan ?
and project raodmap ????

**Comment by nourBerro** [comment]
You can create git repo and share it with me  and write a roadmap.

**Comment by Diaskhan** [comment]
There got a problem. Vision of concept must be synchronized with our different opinion !
That's why need more close conversation ! :)

**Comment by roger-castaldo** [comment]
I honestly have no interest in integrating this with an ecm system, sorry.

**Comment by Diaskhan** [comment]
Ure developing aiming to BPM system ?? What a main goal, that u developed ??
Because, there having ecm,crm systems,midleware systems, Do ure platform has decision engine ?
Actually we searching bpmn midleware credit organization !

**Comment by Diaskhan** [comment]
Roger could show u,re system ? Could we buy it ???

**Comment by roger-castaldo** [comment]
I need a couple of days to stand up a demo of the system, I will contact you with details once its up and ready.  

The software is still in beta testing.

As for capabilities, it uses this library at its core to run the business processes, but has extensions into it for web forms, sending emails, and a few other extensions.  At its core it has the ability to be expanded with outside calls, either through a script task, or implementing your own modules that can be interfaced with in the process builder.  Basically the idea behind it is a business process engine with the ability for users to start and execute processes through web based forms.  Outside of the engine rules and forms, it honestly doesn't care what you do, if you use external api cals to an ecm, crm, etc it will simply make the calls along the process as defined.

As far as purchasing/licensing the product, I have not gotten into that stage yet, as stated the system is still in beta and needs more thorough testing.

**Comment by Diaskhan** [comment]
Actually i'am work in MicroCredit organization. And we some plans to do 
credit conveyor ! 

credit conveyor similar to Ibm bpm, or another bpm systems like camunda !

**Comment by roger-castaldo** [comment]
please contact me at bpmn.engine@gmail.com for url and login details of the demo server.
