### ISSUE TITLE
Its not bpmn engine 

### ISSUE THREAD

**Issue by Diaskhan** [roger-castaldo/BPMEngine#6]
Its not bpmn engine, its etl engine with bpmn notation ! Created parently for linear executing or web services that have one role to exexute ! 

Roger is that minds looks like a true ?

**Comment by roger-castaldo** [comment]
No it is a bpmn2.0 compliant engine.  You can create as many process instances as you wish by simply cloning an already constructed business process, or declaring a new one with the same bpmn2.0 document.  

As far as single roles to execute, that by its nature is a business process, a definition of a set of steps to execute in a given order to handle a given process.  BPMN 2.0 does duppost parallel branching, which the engine does support and execute in a non-linear method.

The basic idea behind this engine is to allow a black boxing of a business process, how the programmer feeds the process and interacts with the process is entirely up to them.  I am currently beta testing a closed source web application that uses this as its core for the business processes but allows end users to design and develop them with forms and backends itself into a database for storing the processes and states.
