### ISSUE TITLE
Serilization

### ISSUE THREAD

**Issue by Diaskhan** [roger-castaldo/BPMEngine#7]
Hie roger waht about serilization when task executes? And transactional support ?

**Comment by roger-castaldo** [comment]
Serialization (if you are talking about variable values).  That is limited to the foloowing types DateTime, Integer, Short, Long, Double, Decimal, String, Char, Boolean, Float, Byte, Null, File, Hashtable.   These values can be arrays as well.

As for transactional support, I am not sure what you mean.  If you are talking executing multiple instances of a single process definition, then you would simply use BusinessProcess.Clone() to create more than one instance of the process.  If you are storing the process state, implement the delegate OnStateChange.  This will be triggered any time a new log line entry is placed into the state, or a step status has changed in the process, or a variable value has been changed, or a step has been suspended, or the process itself has been suspended.

**Comment by Diaskhan** [comment]
I.m talking about when process is executes the state of process must persist to database! When for example we reloading our web app!

**Comment by roger-castaldo** [comment]
To persist to a database, the how is up to you but again implementing an OnStateChange handler would allow for that by inserting the resulting XmlDocument content into a database.  As for hosting it within a web application, when the website is shutting down, you would have to call Suspend on all active business processes which will cause them all to send a final state change once the suspension is complete.

As for the Reload, again load the business process using its definition.  This would then be followed up with each instance of the process calling the function LoadState and supplying the stored XmlDocument.  If the process was suspended properly then you would follow this up with a call to the function Resume().
