### ISSUE TITLE
 Are there project-related documents and sample projects?

### ISSUE THREAD

**Issue by geffzhang** [roger-castaldo/BPMEngine#8]
I'm interested this project，Are there project-related documents and sample projects, no more detailed documentation and sample projects on how to use them

**Comment by roger-castaldo** [comment]
currently there is not, once I get a change I am going to attempt to build a proper wiki to explain full usage.

**Comment by roger-castaldo** [comment]
I have updated the Wiki to define/explain the delegate calls and aspects of a Business Process.  When I have some more time I will attempt to produce a sample definition and code to interface with it.

**Comment by roger-castaldo** [comment]
Attached is a sample project code file and sample process designed to be run as a console application linking the engine library to execute the process.

[TestApplication.zip](https://github.com/roger-castaldo/BPMEngine/files/2150105/TestApplication.zip)

**Comment by roger-castaldo** [comment]
closing with attached sample code and process
